# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://annafil.github.io/
baseurl: /a/
title: Anna Filippova
author: Anna Filippova
description: PhD Candidate. Organizational Hacker. Nerd.
avatar: profile3.png
email: annaf@u.nus.edu
#github: annafil # username
twitter: anna_fil
linkedin: annafilippova
#stackoverflow: username   e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
